version: '3.8'

services:
  web:
    build: .
    command: ["gunicorn", "survey_project.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db  # Ensure this points to the 'db' service

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: survey_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thanya@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

