version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
   
  db:
    image: postgres
    environment:
      POSTGRES_DB: survey_db  # This should match the NAME in your Django settings.py
      POSTGRES_USER: postgres  # This should match the USER in your Django settings.py
      POSTGRES_PASSWORD: thanya@123  # This should match the PASSWORD in your Django settings.py
    ports:
      - "5432:5432"  # Exposing PostgreSQL port is okay for external access (optional)

