# Generated by Django 5.0.6 on 2025-03-05 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_expense', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('coffee_expense', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('biscuit_expense', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('smoking_expense', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
