# Generated by Django 5.1.6 on 2025-03-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0003_alter_surveyresponse_submitted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
