# Generated by Django 5.1.6 on 2025-03-12 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0004_survey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
