# Generated by Django 5.1.7 on 2025-04-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0005_delete_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='user_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
