# Generated by Django 5.1.7 on 2025-04-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0006_surveyresponse_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresponse',
            name='user_email',
        ),
    ]
