# Generated by Django 5.0.7 on 2025-04-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_app', '0007_remove_surveyresponse_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
